In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.3.1'

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [4]:
df.shape

(9704, 11)

In [5]:
df['fuel_type'].nunique()  # Number of unique values in the column

2

In [6]:
df['fuel_type'].value_counts()

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

In [7]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [8]:
df['origin'].value_counts()

origin
Europe    3254
Asia      3247
USA       3203
Name: count, dtype: int64

In [9]:
df[
    df['origin'] == 'Asia'
].describe()   

engine_displacement  num_cylinders   horsepower  vehicle_weight  \
count          3247.000000    3099.000000  3013.000000     3247.000000   
mean            200.052356       4.010326   150.303352     3006.292228   
std              49.287252       1.971199    30.257169      502.434626   
min              30.000000       0.000000    40.000000     1223.298226   
25%             170.000000       3.000000   130.000000     2665.518985   
50%             200.000000       4.000000   150.000000     2988.585737   
75%             230.000000       5.000000   171.000000     3345.355571   
max             370.000000      11.000000   245.000000     4661.144932   

       acceleration   model_year    num_doors  fuel_efficiency_mpg  
count   2933.000000  3247.000000  3072.000000          3247.000000  
mean      15.036754  2011.489375    -0.001628            14.973830  
std        2.488340     6.704607     1.051428             2.578345  
min        6.400000  2000.000000    -4.000000             6.886245  
25%       13.300000  2006.000000    -1.000000            13.252010  
50%       15.100000  2012.000000     0.000000            15.034670  
75%       16.700000  2017.000000     1.000000            16.726318  
max       22.700000  2023.000000     4.000000            23.759123

In [10]:
df['horsepower'].describe()

count    8996.000000
mean      149.657292
std        29.879555
min        37.000000
25%       130.000000
50%       149.000000
75%       170.000000
max       271.000000
Name: horsepower, dtype: float64

In [11]:
df['horsepower'].value_counts()

horsepower
152.0    142
145.0    141
151.0    134
148.0    130
141.0    130
        ... 
40.0       1
57.0       1
245.0      1
252.0      1
61.0       1
Name: count, Length: 192, dtype: int64

In [12]:
df['horsepower'].fillna(df['horsepower'].mode()[0]).describe()

count    9704.000000
mean      149.828215
std        28.775248
min        37.000000
25%       131.000000
50%       152.000000
75%       168.000000
max       271.000000
Name: horsepower, dtype: float64

In [13]:
X = df[
    df['origin'] == 'Asia'
][['vehicle_weight', 'model_year']].head(7).values

In [14]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [15]:
X_trans = X.T
X_trans

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [16]:
XTX = X_trans.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [17]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [18]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [19]:
w = XTX_inv.dot(X_trans).dot(y)
w

array([0.01386421, 0.5049067 ])

In [20]:
w.sum()

np.float64(0.5187709081074016)