<center><h1>Linear Algebra</h1></center>

In [1]:
import numpy as np

## Vector operations

In [2]:
u = np.array([2, 4, 5, 6])
u

array([2, 4, 5, 6])

In [3]:
v = np.array([1, 0, 0, 2])
v

array([1, 0, 0, 2])

In [4]:
u + v

array([3, 4, 5, 8])

In [5]:
# Vector-vector multiplication (dot product)
u * v

array([ 2,  0,  0, 12])

## Multiplication

### Vector-vector muliplication

In [6]:
u = np.array([2, 4, 5, 6])
u.shape[0]

4

In [7]:
v = np.array([1, 0, 0, 2])
v.shape[0]

4

In [8]:
def vector_vector_muliplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [9]:
vector_vector_muliplication(u, v)

np.float64(14.0)

In [10]:
# Numpy function
u.dot(v) # or v.dot(u)

np.int64(14)

### Matrix-vector muliplication

In [11]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

In [12]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [13]:
U.shape[1] # column shape

4

In [14]:
v.shape[0] # row shape

4

In [15]:
def martix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_muliplication(U[i], v)

    return result

In [16]:
martix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [17]:
U.dot(v)

array([14,  5,  5])

### Matrix-matrix muliplication

In [18]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

In [19]:
U.shape[1]

4

In [20]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])

In [21]:
V.shape[0]

4

In [22]:
def matrix_matrix_muliplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_rows):
        for j in range(num_cols):
            result[i, j] = vector_vector_muliplication(U[i], V[:, j])

    return result

In [23]:
matrix_matrix_muliplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [24]:
np.dot(U, V) # or U.dot(V) , V.dot(U)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity Matrix

In [25]:
# Squar matrix with diagonal = 1, and others are 0
## U.I = U
## I.U = U

I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [27]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inverse Matrix

In [28]:
# A^-1 A = I
Vs = V[[0, 1, 2]] # Subset of mateix V (first 3 rows)
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [29]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [30]:
Vs.dot(Vs_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])