<center><h1>Introduction to Numpy</h1></center>

In [1]:
import numpy as np

## Creating arrays

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
a = np.array([1, 2, 3, 5 ,7 ,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [6]:
a[2] = 10

In [7]:
a

array([ 1,  2, 10,  5,  7, 12])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimensional arrays

In [11]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [13]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
n[0,1]

np.int64(2)

In [15]:
n[0,1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [16]:
n[0] #Row number

array([ 1, 20,  3])

In [17]:
n[1] #Row number

array([4, 5, 6])

In [18]:
n[2] = [1, 1, 1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [19]:
n[:, 1] # Column number (leave row empty with :)

array([20,  5,  1])

In [20]:
n[:] #everything

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [21]:
n[:, 2]

array([3, 6, 1])

In [22]:
n[:, 2] = [0, 1, 2] #Change last column
n        

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

## Randomly generated arrays

In [23]:
np.random.seed(2) # to fix the same random numbers
np.random.rand(5, 2) #rows and columns (between 0 and 1)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [24]:
np.random.seed(2) # to fix the same random numbers
np.random.randn(5, 2) # Standard normal distribution (add n)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [25]:
np.random.seed(2) # to fix the same random numbers
100 * np.random.rand(5, 2) #for numbers (between 0 and 100)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [26]:
np.random.seed(2) # to fix the same random numbers
np.random.randint(low= 0, high= 100, size= (5,2)) #customized

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [27]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [28]:
print(a + 1)
print(a - 1)
print(a * 2)
print(a / 2)
print(10 + (a*2) ** 2)

[1 2 3 4 5]
[-1  0  1  2  3]
[0 2 4 6 8]
[0.  0.5 1.  1.5 2. ]
[10 14 26 46 74]


In [29]:
b = 10 + (a*2) ** 2
b

array([10, 14, 26, 46, 74])

In [30]:
a

array([0, 1, 2, 3, 4])

In [31]:
a + b # two arrays

array([10, 15, 28, 49, 78])

## Comparison operations

In [32]:
a

array([0, 1, 2, 3, 4])

In [33]:
a >= 2

array([False, False,  True,  True,  True])

In [34]:
b

array([10, 14, 26, 46, 74])

In [35]:
a > b

array([False, False, False, False, False])

In [36]:
a[a > b]

array([], dtype=int64)

In [37]:
b[b > a]

array([10, 14, 26, 46, 74])

## Summarizing operations

In [38]:
a

array([0, 1, 2, 3, 4])

In [39]:
a.sum()

np.int64(10)

In [40]:
a.min()

np.int64(0)

In [41]:
a.max()

np.int64(4)

In [42]:
a.mean()

np.float64(2.0)

In [43]:
a.std()

np.float64(1.4142135623730951)